spring:
  application:
    name: desafio
  r2dbc:
    url: r2dbc:h2:mem:///desafio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  flyway:
    enabled: true
    url: jdbc:h2:mem:desafio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
  webflux:
    base-path: /desafio
